package com.pear.dao;

import com.pear.model.login;

public interface loginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    int insert(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    int insertSelective(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    login selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    int updateByPrimaryKeySelective(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    int updateByPrimaryKey(login record);
}