package com.pear.model;

import java.io.Serializable;

public class login implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.username
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user_id
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.username
     *
     * @return the value of login.username
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.username
     *
     * @param username the value for login.username
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user_id
     *
     * @return the value of login.user_id
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user_id
     *
     * @param userId the value for login.user_id
     *
     * @mbggenerated Tue Feb 16 16:29:44 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}